spring:
  profiles:
    active: development
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    open-in-view: false
server:
  port: 7311
alibaba:
  cloud:
    access-key-id: ${ALIBABA_CLOUD_ACCESS_KEY_ID}
    access-key-secret: ${ALIBABA_CLOUD_ACCESS_KEY_SECRET}
    sms:
      endpoint: dysmsapi.aliyuncs.com
      sign-name: 阿里云短信测试
      template-code: SMS_154950909
---
spring:
  config:
    activate:
      on-profile: development
  datasource:
    url: jdbc:mysql:///dewey?serverTimezone=GMT%2B8
---
spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: jdbc:mysql://mysql/dewey?serverTimezone=GMT%2B8
  data:
    redis:
      host: redis
